# Generated by Django 6.0.2 on 2026-02-26 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_merge_0003_add_category_fk_0003_create_m2m_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
